---
title: "SLiM analysis"
author: "Gabriel, Douhan, Léo"
date: "2024-11-28"
output: html_document
---
```{r}
library(ggplot2)
library(patchwork)
```

# Load the data

## random_mating

```{r}

# Load random mating

rm_df <- read.table("C:/Users/besan/OneDrive/Bureau/Master MLS/Genpop/BreedingSimulator-main/BreedingSimulator/BreedingSimulator/1_Outputs/1_Random-Relatedness/random-relatedness_5000burn_100gen_1_popstats.txt", header = T)


for(i in 2:2){
  df <- read.table(paste0("C:/Users/besan/OneDrive/Bureau/Master MLS/Genpop/BreedingSimulator-main/BreedingSimulator/BreedingSimulator/1_Outputs/1_Random-Relatedness/random-relatedness_5000burn_100gen_", i, "_popstats.txt"), header = T)
  rm_df <- rbind(rm_df, df)
}

rm_df$Generation <- rm_df$Generation - 5000
rm_df$PopulationID <- rep(1:2, each = 101)

# load genetic_load regime

genload_df <- read.table("C:/Users/besan/OneDrive/Bureau/Master MLS/Genpop/BreedingSimulator-main/BreedingSimulator/BreedingSimulator/1_Outputs/3_Genetic-Load/genetic_load_5000burn_100gen_1_popstats.txt", header = T)


for(i in 2:2){
  df <- read.table(paste0("C:/Users/besan/OneDrive/Bureau/Master MLS/Genpop/BreedingSimulator-main/BreedingSimulator/BreedingSimulator/1_Outputs/3_Genetic-Load/genetic_load_5000burn_100gen_", i, "_popstats.txt"), header = T)
  genload_df <- rbind(genload_df, df)
}
genload_df$Generation <- genload_df$Generation - 5000
genload_df$PopulationID <- rep(1:2, each = 101)
#load relatedness model

related_df <- read.table("C:/Users/besan/OneDrive/Bureau/Master MLS/Genpop/BreedingSimulator-main/BreedingSimulator/BreedingSimulator/1_Outputs/2_Relatedness/relatedness_10000burn_100gen_1_popstats.txt", header = T)


for(i in 2:40){
  df <- read.table(paste0("C:/Users/besan/OneDrive/Bureau/Master MLS/Genpop/BreedingSimulator-main/BreedingSimulator/BreedingSimulator/1_Outputs/2_Relatedness/relatedness_10000burn_100gen_", i, "_popstats.txt"), header = T)
  related_df <- rbind(related_df, df)
}

related_df$Generation <- related_df$Generation -10000
related_df$PopulationID <- rep(1:41, each = 101)
#load genetic + relatedness

mixed_df <- read.table("C:/Users/besan/OneDrive/Bureau/Master MLS/Genpop/BreedingSimulator-main/BreedingSimulator/BreedingSimulator/1_Outputs/4_Mixed/mixed_5000burn_100gen_1_popstats.txt", header = T)


for(i in 2:2){
  df <- read.table(paste0("C:/Users/besan/OneDrive/Bureau/Master MLS/Genpop/BreedingSimulator-main/BreedingSimulator/BreedingSimulator/1_Outputs/4_Mixed/mixed_5000burn_100gen_", i, "_popstats.txt"), header = T)
  mixed_df <- rbind(mixed_df, df)
}
mixed_df$PopulationID <- rep(1:2, each = 101)
mixed_df$Generation <- mixed_df$Generation -5000

# Load full random mating

random_df <- read.table("C:/Users/besan/OneDrive/Bureau/Master MLS/Genpop/BreedingSimulator-main/BreedingSimulator/BreedingSimulator/1_Outputs/0_Random/random_5000burn_100gen_1_popstats.txt", header = T)


for(i in 2:2){
  df <- read.table(paste0("C:/Users/besan/OneDrive/Bureau/Master MLS/Genpop/BreedingSimulator-main/BreedingSimulator/BreedingSimulator/1_Outputs/0_Random/random_5000burn_100gen_", i, "_popstats.txt"), header = T)
  random_df <- rbind(random_df, df)
}

random_df$Generation <- random_df$Generation - 5000
random_df$PopulationID <- rep(1:2, each = 101)
```

Now we do the mean of every replicat at each generation for genload

```{r}
heterozygo <- c()
genetic_load <- c()
realized_load <- c()
fitness <- c()
gen <- c()
for(i in 1:101){
  generation <- genload_df[genload_df$Generation == i,]
  heterozygo <- c(heterozygo, mean(generation$UniqueMutations))
  genetic_load <- c(genetic_load, mean(generation$totalLoad))
  realized_load <- c(realized_load, mean(generation$RelzLoad))
  fitness <- c(fitness, mean(generation$MeanFitness))
  gen <- c(gen, i)
}
mean_genload_df <- as.data.frame(cbind(gen, heterozygo, genetic_load, realized_load, fitness))
colnames(mean_genload_df) <- c("generation", "heterozygosity", "genetic_load", "realized_load", "fitness")
```
now for random mating

```{r}
heterozygo <- c()
genetic_load <- c()
realized_load <- c()
fitness <- c()
gen <- c()
for(i in 1:101){
  generation <- rm_df[rm_df$Generation == i,]
  heterozygo <- c(heterozygo, mean(generation$UniqueMutations))
  genetic_load <- c(genetic_load, mean(generation$totalLoad))
  realized_load <- c(realized_load, mean(generation$RelzLoad))
  fitness <- c(fitness, mean(generation$MeanFitness))
  gen <- c(gen, i)
}
mean_rm_df <- as.data.frame(cbind(gen, heterozygo, genetic_load, realized_load, fitness))
colnames(mean_rm_df) <- c("generation", "heterozygosity", "genetic_load", "realized_load", "fitness")
```

now for relatedness

```{r}
heterozygo <- c()
genetic_load <- c()
realized_load <- c()
fitness <- c()
gen <- c()
for(i in 1:101){
  generation <- related_df[related_df$Generation == i,]
  heterozygo <- c(heterozygo, mean(generation$UniqueMutations))
  genetic_load <- c(genetic_load, mean(generation$totalLoad))
  realized_load <- c(realized_load, mean(generation$RelzLoad))
  fitness <- c(fitness, mean(generation$MeanFitness))
  gen <- c(gen, i)
}
mean_related_df <- as.data.frame(cbind(gen, heterozygo, genetic_load, realized_load, fitness))
colnames(mean_related_df) <- c("generation", "heterozygosity", "genetic_load", "realized_load", "fitness")
```

now for gen_and_related

```{r}
heterozygo <- c()
genetic_load <- c()
realized_load <- c()
fitness <- c()
gen <- c()
for(i in 1:101){
  generation <- gen_and_rel_df[gen_and_rel_df$Generation == i,]
  heterozygo <- c(heterozygo, mean(generation$uniquemutation))
  genetic_load <- c(genetic_load, mean(generation$totalLoad))
  realized_load <- c(realized_load, mean(generation$RelzLoad))
  fitness <- c(fitness, mean(generation$fitness))
  gen <- c(gen, i)
}
mean_gen_and_rel_df <- cbind(gen, heterozygo, genetic_load, realized_load, fitness)
colnames(mean_gen_and_rel_df) <- c("generation", "heterozygosity", "genetic_load", "realized_load", "fitness")
```

now for full random

```{r}
heterozygo <- c()
genetic_load <- c()
realized_load <- c()
fitness <- c()
gen <- c()
for(i in 1:101){
  generation <- random_df[random_df$Generation == i,]
  heterozygo <- c(heterozygo, mean(generation$UniqueMutations))
  genetic_load <- c(genetic_load, mean(generation$totalLoad))
  realized_load <- c(realized_load, mean(generation$RelzLoad))
  fitness <- c(fitness, mean(generation$MeanFitness))
  gen <- c(gen, i)
}
mean_random_df <- as.data.frame(cbind(gen, heterozygo, genetic_load, realized_load, fitness))
colnames(mean_random_df) <- c("generation", "heterozygosity", "genetic_load", "realized_load", "fitness")
```


```{r}
realized_graph <- ggplot() + geom_line(data = mean_genload_df, aes(x = generation, y = realized_load), color = "indianred1", size = 1 ) +  geom_line(data = mean_rm_df, aes(x = generation, y = realized_load), color = "orchid1", size = 1 ) + geom_line(data = mean_random_df, aes(x = generation, y = realized_load), color = "yellow1", size = 1 )+ geom_line(data = mean_related_df, aes(x = generation, y = realized_load), color = "skyblue1", size = 1 ) + labs(x = "Generations", y = "Realized load") + 
  theme(
    plot.background = element_rect(fill = "black"),
    panel.background = element_rect(fill = "black"),
    panel.grid.major = element_line(color = "gray30"),
    panel.grid.minor = element_line(color = "gray20"),
    axis.text = element_text(color = "white"),
    axis.title = element_text(color = "white"),
    plot.title = element_text(color = "white", hjust = 0.5),
    legend.background = element_rect(fill = "black"),
    legend.text = element_text(color = "white") 
  )

load_graph <- ggplot() + geom_line(data = mean_genload_df, aes(x = generation, y = genetic_load), color = "indianred1", size = 1 ) +  geom_line(data = mean_rm_df, aes(x = generation, y = genetic_load), color = "orchid1", size = 1 ) + geom_line(data = mean_random_df, aes(x = generation, y = genetic_load), color = "yellow1", size = 1 )+ geom_line(data = mean_related_df, aes(x = generation, y = genetic_load), color = "skyblue1", size = 1 ) + labs(x = "Generations", y = "Genetic load") + theme(
    plot.background = element_rect(fill = "black"),
    panel.background = element_rect(fill = "black"),
    panel.grid.major = element_line(color = "gray30"),
    panel.grid.minor = element_line(color = "gray20"),
    axis.text = element_text(color = "white"),
    axis.title = element_text(color = "white"),
    plot.title = element_text(color = "white", hjust = 0.5),
    legend.background = element_rect(fill = "black"),
    legend.text = element_text(color = "white") 
  )
fitness_graph <- ggplot() + geom_line(data = mean_genload_df, aes(x = generation, y = fitness), color = "indianred1", size = 1 ) + geom_line(data = mean_rm_df, aes(x = generation, y = fitness), color = "orchid1", size = 1 ) + geom_line(data = mean_random_df, aes(x = generation, y = fitness), color = "yellow1", size = 1 )+ geom_line(data = mean_related_df, aes(x = generation, y = fitness), color = "skyblue1", size = 1 ) + labs(x = "Generations", y = "Fitness") + theme(
    plot.background = element_rect(fill = "black"),
    panel.background = element_rect(fill = "black"),
    panel.grid.major = element_line(color = "gray30"),
    panel.grid.minor = element_line(color = "gray20"),
    axis.text = element_text(color = "white"),
    axis.title = element_text(color = "white"),
    plot.title = element_text(color = "white", hjust = 0.5),
    legend.background = element_rect(fill = "black"),
    legend.text = element_text(color = "white") 
      
  )

hetero_graph <- ggplot() + geom_line(data = mean_genload_df, aes(x = generation, y = heterozygosity), color = "indianred1", size = 1 ) + geom_line(data = mean_rm_df, aes(x = generation, y = heterozygosity), color = "orchid1", size = 1 ) + geom_line(data = mean_random_df, aes(x = generation, y = heterozygosity), color = "yellow1", size = 1 )+ geom_line(data = mean_related_df, aes(x = generation, y = heterozygosity), color = "skyblue1", size = 1 ) + labs(x = "Generations", y = "Number of unique mutation") + theme(
    plot.background = element_rect(fill = "black"),
    panel.background = element_rect(fill = "black"),
    panel.grid.major = element_line(color = "gray30"),
    panel.grid.minor = element_line(color = "gray20"),
    axis.text = element_text(color = "white"),
    axis.title = element_text(color = "white"),
    plot.title = element_text(color = "white", hjust = 0.5),
    legend.background = element_rect(fill = "black"),
    legend.text = element_text(color = "white") 
  )

combined_plot <- load_graph + realized_graph + fitness_graph + hetero_graph + plot_layout(ncol = 4) + plot_annotation(theme = theme(plot.background = element_rect(fill = "black")))
ggsave(
  filename = "C:/Users/besan/OneDrive/Bureau/Master MLS/Genpop/BreedingSimulator-main/BreedingSimulator/BreedingSimulator/2_R-Workspace/combined_plot.png",  # Full file path
  plot = combined_plot,            # Plot object to save
  width = 12,              # Width in inches
  height = 6,             # Height in inches
  dpi = 600               # Resolution
)
print(combined_plot)
```

plot the legend 

```{r}

library(cowplot)

# Create a dummy data frame for the legend
legend_data <- data.frame(
  x = c(1, 2, 3),  # Dummy x-values
  y = c(1, 1, 1),  # Dummy y-values
  group = factor(c("Minimize load", "Random mating related", "Random mating"))  # Factor for legend
)

# Generate a plot with an enlarged legend
legend_plot <- ggplot(legend_data, aes(x = x, y = y, color = group)) +
  geom_point(size = 5) +  # Add dummy points for the legend
  scale_color_manual(
    values = c(
      "Minimize load" = "indianred1",
      "Random mating related" = "orchid1",
      "Random mating" = "yellow1"
    )
  ) +
  labs(color = "Group Legend") +  # Set the legend title
  theme_minimal() +
  theme(
    legend.position = "bottom",          # Place the legend at the bottom
    legend.key.size = unit(2.5, "cm"),   # Increase size of legend keys
    legend.text = element_text(size = 16, color = "white"),  # Increase size of legend text
    legend.title = element_text(size = 18, color = "white"), # Increase size of legend title
    legend.key = element_rect(fill = "black"),  # Black background for legend keys
    panel.background = element_rect(fill = "black"),
    plot.background = element_rect(fill = "black"),
    axis.title = element_blank(),
    axis.text = element_blank(),
    axis.ticks = element_blank(),
    panel.grid = element_blank()
  )
# Extract only the legend part
legend_plot
```

# Statistical analysis

## Student t test within each regimes between the hundreds replicates

```{r}

# loading the end points for every replicates
end_random_related <- rm_df[rm_df$Generation == 101,]
end_random <- random_df[random_df$Generation == 101,]
end_load <- genload_df[genload_df$Generation == 101,]
end_related <- related_df[related_df$Generation == 101,]
end_mixed <- mixed_df[mixed_df$Generation == 101,]
```

```{r}
batch_ttest_load <- t.test(end_load$RelzLoad) ; batch_ttest_load
batch_ttest_random <- t.test(end_random$RelzLoad) ; batch_ttest_random
batch_ttest_random_related <- t.test(end_random_related$RelzLoad) ; batch_ttest_random_related
batch_ttest_related <- t.test(end_related$RelzLoad)
batch_ttest_mixed <- t.test(end_mixed$RelzLoad)
```

## Anova between all the regimes 100 batches

```{r}
end_load$regime <- "load"
end_random_related$regime <- "random_related"
end_random$regime <- "random"
end_related$regime <- "related"
end_mixed$regime <- "mixed"
model_df <- rbind(end_load, end_mixed, end_random, end_random_related, end_related)
model_df$regime <- factor(model_df$regime)
```
```{r}
mod <- aov(model_df$RelzLoad ~ model_df$regime)
anova(mod)
```














